version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass12345
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped
    
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin123
        volumes:
            - ./store_files:/data/db
        depends_on:
            - mongodb
        ports:
            - 8081:8081
        healthcheck:
            test:  wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped

    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
            - mongodb
        environment:
            - INSTALL_MONGO=y
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
            - AIRFLOW__SMTP__SMTP_USER=example@gmail.com
            - AIRFLOW__SMTP__SMTP_PASSWORD=hdwiondmyyobhlto
            - AIRFLOW__SMTP__SMTP_PORT=587
            - AIRFLOW__SMTP__SMTP_MAIL_FROM=Airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - mongodata

            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
volumes:
    mongodata: